/**
 * LeverageTradingV2 — ABI pentru frontend (BSC deploy la adresa din runtime-config / contractMap).
 * SSOT sursă Solidity: C:/Users/bits/Desktop/remix/OTA/BSC/TradeOTA/LeverageTradingV2.sol
 * V1 local a fost eliminat din repo; comportament on-chain = artefact deployat + sursa V2 din remix.
 */

const LeveragePositionTuple = [
  { name: 'positionId', type: 'uint256', internalType: 'uint256' },
  { name: 'user', type: 'address', internalType: 'address' },
  { name: 'collateralToken', type: 'address', internalType: 'address' },
  { name: 'borrowedToken', type: 'address', internalType: 'address' },
  { name: 'collateralAmount', type: 'uint256', internalType: 'uint256' },
  { name: 'borrowedAmount', type: 'uint256', internalType: 'uint256' },
  { name: 'interestAccrued', type: 'uint256', internalType: 'uint256' },
  { name: 'leverageRatio', type: 'uint256', internalType: 'uint256' },
  { name: 'entryPrice', type: 'uint256', internalType: 'uint256' },
  { name: 'liquidationPrice', type: 'uint256', internalType: 'uint256' },
  { name: 'interestRate', type: 'uint256', internalType: 'uint256' },
  { name: 'openedAt', type: 'uint256', internalType: 'uint256' },
  { name: 'lastInterestUpdate', type: 'uint256', internalType: 'uint256' },
  { name: 'closedAt', type: 'uint256', internalType: 'uint256' },
  { name: 'isActive', type: 'bool', internalType: 'bool' },
];

/** Struct CFDPosition — LeverageTradingV2 */
const CFDPositionTupleV2 = [
  { name: 'positionId', type: 'uint256', internalType: 'uint256' },
  { name: 'user', type: 'address', internalType: 'address' },
  { name: 'assetId', type: 'bytes32', internalType: 'bytes32' },
  { name: 'settlementToken', type: 'address', internalType: 'address' },
  { name: 'marginAmount', type: 'uint256', internalType: 'uint256' },
  { name: 'leverageBps', type: 'uint256', internalType: 'uint256' },
  { name: 'isLong', type: 'bool', internalType: 'bool' },
  { name: 'entryPrice', type: 'uint256', internalType: 'uint256' },
  { name: 'openedAt', type: 'uint256', internalType: 'uint256' },
  { name: 'isActive', type: 'bool', internalType: 'bool' },
  { name: 'takeProfitPrice', type: 'uint256', internalType: 'uint256' },
  { name: 'stopLossPrice', type: 'uint256', internalType: 'uint256' },
];

const abi = [
  { inputs: [], name: 'BPS_DENOMINATOR', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'CLOSE_REASON_BANKRUPT', outputs: [{ type: 'uint8' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'CLOSE_REASON_MANUAL', outputs: [{ type: 'uint8' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'CLOSE_REASON_SL', outputs: [{ type: 'uint8' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'CLOSE_REASON_TP', outputs: [{ type: 'uint8' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'cfdPositionCounter', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'defaultSettlementToken', outputs: [{ type: 'address' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'lendingPool', outputs: [{ type: 'address' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'maxCfdLeverageBps', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'maxLeverageRatio', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'maxPositionsPerUser', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'positionCounter', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'priceMaxAgeSeconds', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'paused', outputs: [{ type: 'bool' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'totalPositions', outputs: [{ type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'userVault', outputs: [{ type: 'address' }], stateMutability: 'view', type: 'function' },
  {
    inputs: [{ name: 'positionId', type: 'uint256' }],
    name: 'positions',
    outputs: [{ components: LeveragePositionTuple, internalType: 'struct LeverageTradingV2.LeveragePosition', type: 'tuple' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'user', type: 'address' }],
    name: 'userPositions',
    outputs: [{ type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'user', type: 'address' }],
    name: 'userCFDPositions',
    outputs: [{ type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'user', type: 'address' }],
    name: 'userActiveSpotCount',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'user', type: 'address' }],
    name: 'userActiveCfdCount',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'collateralToken', type: 'address' },
      { name: 'borrowedToken', type: 'address' },
    ],
    name: 'getCurrentPrice',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'assetId', type: 'bytes32' }],
    name: 'getCFDPrice',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'positionId', type: 'uint256' }],
    name: 'getPosition',
    outputs: [{ components: LeveragePositionTuple, internalType: 'struct LeverageTradingV2.LeveragePosition', type: 'tuple' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'positionId', type: 'uint256' }],
    name: 'getCFDPosition',
    outputs: [{ components: CFDPositionTupleV2, internalType: 'struct LeverageTradingV2.CFDPosition', type: 'tuple' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'positionId', type: 'uint256' }],
    name: 'getCFDSettlementPreview',
    outputs: [
      { name: 'markPrice', type: 'uint256' },
      { name: 'pnlRaw', type: 'int256' },
      { name: 'marginReturned', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'positionId', type: 'uint256' }],
    name: 'calculateLiquidationPrice',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'positionId', type: 'uint256' }],
    name: 'getSpotDebtTotal',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'positionId', type: 'uint256' }],
    name: 'getSpotPositionTotalRepay',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'token', type: 'address' }],
    name: 'getTreasuryBalance',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'collateralToken', type: 'address' },
      { name: 'borrowedToken', type: 'address' },
      { name: 'collateralAmount', type: 'uint256' },
      { name: 'leverageRatio', type: 'uint256' },
    ],
    name: 'openLeveragePosition',
    outputs: [{ name: 'positionId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [{ name: 'positionId', type: 'uint256' }], name: 'closeLeveragePosition', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [
      { name: 'positionId', type: 'uint256' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'addCollateral',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'positionId', type: 'uint256' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'removeCollateral',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [{ name: 'positionId', type: 'uint256' }], name: 'liquidatePosition', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [
      { name: 'assetId', type: 'bytes32' },
      { name: 'settlementToken', type: 'address' },
      { name: 'marginAmount', type: 'uint256' },
      { name: 'leverageBps', type: 'uint256' },
      { name: 'isLong', type: 'bool' },
    ],
    name: 'openCFDPosition',
    outputs: [{ name: 'positionId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'assetId', type: 'bytes32' },
      { name: 'marginAmount', type: 'uint256' },
      { name: 'leverageBps', type: 'uint256' },
      { name: 'isLong', type: 'bool' },
    ],
    name: 'openCFDPosition',
    outputs: [{ name: 'positionId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'assetId', type: 'bytes32' },
      { name: 'settlementToken', type: 'address' },
      { name: 'marginAmount', type: 'uint256' },
      { name: 'leverageBps', type: 'uint256' },
      { name: 'isLong', type: 'bool' },
      { name: 'takeProfitPrice', type: 'uint256' },
      { name: 'stopLossPrice', type: 'uint256' },
    ],
    name: 'openCFDPositionWithTPSL',
    outputs: [{ name: 'positionId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'assetId', type: 'bytes32' },
      { name: 'marginAmount', type: 'uint256' },
      { name: 'leverageBps', type: 'uint256' },
      { name: 'isLong', type: 'bool' },
      { name: 'takeProfitPrice', type: 'uint256' },
      { name: 'stopLossPrice', type: 'uint256' },
    ],
    name: 'openCFDPositionWithTPSL',
    outputs: [{ name: 'positionId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'positionId', type: 'uint256' },
      { name: 'takeProfitPrice', type: 'uint256' },
      { name: 'stopLossPrice', type: 'uint256' },
    ],
    name: 'setCFDTakeProfitStopLoss',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [{ name: 'positionId', type: 'uint256' }], name: 'closeCFDPosition', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: 'positionId', type: 'uint256' }], name: 'triggerCFDCloseIfTPSL', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: 'positionId', type: 'uint256' }], name: 'triggerCFDCloseIfBankrupt', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_pool', type: 'address' }], name: 'setLendingPool', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [
      { name: 'collateral', type: 'address' },
      { name: 'borrowed', type: 'address' },
      { name: 'feed', type: 'address' },
    ],
    name: 'setTokenPairPriceFeed',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'assetId', type: 'bytes32' },
      { name: 'feed', type: 'address' },
    ],
    name: 'setCFDAssetPriceFeed',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'feed', type: 'address' },
    ],
    name: 'setEurUsdFeed',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [{ name: '_bps', type: 'uint256' }], name: 'setMaxLeverageRatio', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_bps', type: 'uint256' }], name: 'setMaxCfdLeverageBps', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_bps', type: 'uint256' }], name: 'setLiquidationThresholdBps', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_bps', type: 'uint256' }], name: 'setDefaultInterestRateBps', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: '_token', type: 'address' }], name: 'setDefaultSettlementToken', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: 's', type: 'uint256' }], name: 'setPriceMaxAgeSeconds', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: 'n', type: 'uint256' }], name: 'setMaxPositionsPerUser', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [
      { name: 'settlementToken', type: 'address' },
      { name: 'minAmount', type: 'uint256' },
    ],
    name: 'setMinCfdMargin',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'depositReserve',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'withdrawReserve',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [{ name: 'to', type: 'address' }], name: 'recoverNative', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [], name: 'pause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [], name: 'unpause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'positionId', type: 'uint256' },
      { indexed: true, name: 'user', type: 'address' },
      { indexed: false, name: 'collateralToken', type: 'address' },
      { indexed: false, name: 'borrowedToken', type: 'address' },
      { indexed: false, name: 'collateralAmount', type: 'uint256' },
      { indexed: false, name: 'borrowedAmount', type: 'uint256' },
      { indexed: false, name: 'leverageRatio', type: 'uint256' },
      { indexed: false, name: 'entryPrice', type: 'uint256' },
      { indexed: false, name: 'liquidationPrice', type: 'uint256' },
    ],
    name: 'PositionOpened',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'positionId', type: 'uint256' },
      { indexed: true, name: 'user', type: 'address' },
      { indexed: false, name: 'collateralReturned', type: 'uint256' },
      { indexed: false, name: 'totalRepaid', type: 'uint256' },
      { indexed: false, name: 'interestPaid', type: 'uint256' },
    ],
    name: 'PositionClosed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'positionId', type: 'uint256' },
      { indexed: true, name: 'user', type: 'address' },
      { indexed: true, name: 'liquidator', type: 'address' },
      { indexed: false, name: 'collateralSeized', type: 'uint256' },
      { indexed: false, name: 'debtRepaid', type: 'uint256' },
    ],
    name: 'SpotPositionLiquidated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'positionId', type: 'uint256' },
      { indexed: true, name: 'user', type: 'address' },
      { indexed: true, name: 'token', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'newCollateral', type: 'uint256' },
      { indexed: false, name: 'newLiquidationPrice', type: 'uint256' },
    ],
    name: 'CollateralAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'positionId', type: 'uint256' },
      { indexed: true, name: 'user', type: 'address' },
      { indexed: true, name: 'token', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'newCollateral', type: 'uint256' },
      { indexed: false, name: 'newLiquidationPrice', type: 'uint256' },
    ],
    name: 'CollateralRemoved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'positionId', type: 'uint256' },
      { indexed: true, name: 'user', type: 'address' },
      { indexed: false, name: 'assetId', type: 'bytes32' },
      { indexed: false, name: 'settlementToken', type: 'address' },
      { indexed: false, name: 'marginAmount', type: 'uint256' },
      { indexed: false, name: 'leverageBps', type: 'uint256' },
      { indexed: false, name: 'isLong', type: 'bool' },
      { indexed: false, name: 'entryPrice', type: 'uint256' },
    ],
    name: 'CFDPositionOpened',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'positionId', type: 'uint256' },
      { indexed: true, name: 'user', type: 'address' },
      { indexed: false, name: 'pnl', type: 'int256' },
      { indexed: false, name: 'marginReturned', type: 'uint256' },
    ],
    name: 'CFDPositionClosed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'positionId', type: 'uint256' },
      { indexed: true, name: 'user', type: 'address' },
      { indexed: false, name: 'takeProfitPrice', type: 'uint256' },
      { indexed: false, name: 'stopLossPrice', type: 'uint256' },
    ],
    name: 'CFDTakeProfitStopLossSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'positionId', type: 'uint256' },
      { indexed: true, name: 'user', type: 'address' },
      { indexed: false, name: 'closeReason', type: 'uint8' },
      { indexed: false, name: 'triggerPrice', type: 'uint256' },
      { indexed: false, name: 'pnl', type: 'int256' },
      { indexed: false, name: 'marginReturned', type: 'uint256' },
    ],
    name: 'CFDTriggeredClose',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'token', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
    ],
    name: 'ReserveDeposited',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'token', type: 'address' },
      { indexed: true, name: 'to', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
    ],
    name: 'ReserveWithdrawn',
    type: 'event',
  },
];

export { CFDPositionTupleV2, LeveragePositionTuple };
export default abi;
